export const UI_STRINGS = {
  en: {
    nav_courses: "Courses",
    nav_faq: "FAQ",
    nav_blog: "Blog",
    nav_apply: "Apply now",
    footer_explore: "Explore",
    footer_contact: "Contact",
    footer_courses: "Courses",
    footer_blog: "Blog",
    footer_faq: "FAQ",
    footer_certificates: "Certificates",
    footer_talk_advisor: "Talk to an advisor",
    footer_tagline: "Education that turns knowledge into real results — data analytics, languages, and professional skills, in Baku.",
    footer_rights: "All rights reserved.",
    hero_eyebrow: "Baku · A Center for Professional Growth",
    hero_title_line1: "Education that turns",
    hero_title_line2: "knowledge into real results.",
    hero_subtitle:
      "Practical training in data analytics, languages, and professional skills. Our goal isn't just to hand you a certificate — it's to shape you into a competitive specialist in today's job market.",
    hero_cta_courses: "See all courses",
    hero_cta_advisor: "Talk to an advisor",
  },
  az: {
    nav_courses: "Kurslar",
    nav_faq: "Suallar",
    nav_blog: "Bloq",
    nav_apply: "Müraciət et",
    footer_explore: "Naviqasiya",
    footer_contact: "Əlaqə",
    footer_courses: "Kurslar",
    footer_blog: "Bloq",
    footer_faq: "Suallar",
    footer_certificates: "Sertifikatlar",
    footer_talk_advisor: "Məsləhətçi ilə əlaqə",
    footer_tagline: "Biliklərinizi real nəticələrə çevirən təhsil — data analitikası, dillər və peşəkar bacarıqlar üzrə, Bakıda.",
    footer_rights: "Bütün hüquqlar qorunur.",
    hero_eyebrow: "Bakı · Peşəkar İnkişaf Akademiyası",
    hero_title_line1: "Biliklərinizi real",
    hero_title_line2: "nəticələrə çevirən təhsil.",
    hero_subtitle:
      "Data analitikası, dillər və peşəkar bacarıqlar üzrə praktiki təlimlər. Məqsədimiz sadəcə sertifikat təqdim etmək deyil, sizi əmək bazarında rəqabətqabiliyyətli mütəxəssis kimi formalaşdırmaqdır.",
    hero_cta_courses: "Kurslara baxın",
    hero_cta_advisor: "Məsləhətçi ilə danışın",
  },
  ru: {
    nav_courses: "Курсы",
    nav_faq: "Вопросы",
    nav_blog: "Блог",
    nav_apply: "Подать заявку",
    footer_explore: "Навигация",
    footer_contact: "Контакты",
    footer_courses: "Курсы",
    footer_blog: "Блог",
    footer_faq: "Вопросы",
    footer_certificates: "Сертификаты",
    footer_talk_advisor: "Поговорить с консультантом",
    footer_tagline: "Образование, превращающее знания в реальный результат — аналитика данных, языки и профессиональные навыки в Баку.",
    footer_rights: "Все права защищены.",
    hero_eyebrow: "Баку · Центр профессионального развития",
    hero_title_line1: "Образование, превращающее",
    hero_title_line2: "знания в реальный результат.",
    hero_subtitle:
      "Практическое обучение по аналитике данных, языкам и профессиональным навыкам. Наша цель — не просто выдать сертификат, а сделать вас конкурентоспособным специалистом на рынке труда.",
    hero_cta_courses: "Все курсы",
    hero_cta_advisor: "Поговорить с консультантом",
  },
} as const;

export type UiStringKey = keyof typeof UI_STRINGS.en;
