export const UI_STRINGS = {
  en: {
    nav_courses: "Courses",
    nav_faq: "FAQ",
    nav_blog: "Blog",
    nav_apply: "Apply now",
    footer_explore: "Explore",
    footer_contact: "Contact",
    footer_courses: "Courses",
    footer_blog: "Blog",
    footer_faq: "FAQ",
    footer_certificates: "Certificates",
    footer_talk_advisor: "Talk to an advisor",
    footer_tagline: "Practical courses for career growth in Baku — data, languages, and more.",
    footer_rights: "All rights reserved.",
    hero_eyebrow: "Baku · A Center for Professional Growth",
    hero_title_line1: "Skills that point",
    hero_title_line2: "somewhere real.",
    hero_subtitle:
      "From data science to languages, North Star Academy builds practical courses around what actually moves your career forward — not just a certificate, but a real next step.",
    hero_cta_courses: "See all courses",
    hero_cta_advisor: "Talk to an advisor",
  },
  az: {
    nav_courses: "Kurslar",
    nav_faq: "Suallar",
    nav_blog: "Bloq",
    nav_apply: "Müraciət et",
    footer_explore: "Naviqasiya",
    footer_contact: "Əlaqə",
    footer_courses: "Kurslar",
    footer_blog: "Bloq",
    footer_faq: "Suallar",
    footer_certificates: "Sertifikatlar",
    footer_talk_advisor: "Məsləhətçi ilə əlaqə",
    footer_tagline: "Bakıda peşəkar inkişaf üçün kurslar — data, dillər və daha çoxu.",
    footer_rights: "Bütün hüquqlar qorunur.",
    hero_eyebrow: "Bakı · Peşəkar İnkişaf Akademiyası",
    hero_title_line1: "Biliklərinizi real",
    hero_title_line2: "nəticələrə çevirən təhsil.",
    hero_subtitle:
      "Data analitikası, dillər və peşəkar bacarıqlar üzrə praktiki təlimlər. Məqsədimiz sadəcə sertifikat təqdim etmək deyil, sizi əmək bazarında rəqabətqabiliyyətli mütəxəssis kimi formalaşdırmaqdır.",
    hero_cta_courses: "Kurslara baxın",
    hero_cta_advisor: "Məsləhətçi ilə danışın",
  },
  ru: {
    nav_courses: "Курсы",
    nav_faq: "Вопросы",
    nav_blog: "Блог",
    nav_apply: "Подать заявку",
    footer_explore: "Навигация",
    footer_contact: "Контакты",
    footer_courses: "Курсы",
    footer_blog: "Блог",
    footer_faq: "Вопросы",
    footer_certificates: "Сертификаты",
    footer_talk_advisor: "Поговорить с консультантом",
    footer_tagline: "Практические курсы для карьерного роста в Баку — данные, языки и многое другое.",
    footer_rights: "Все права защищены.",
    hero_eyebrow: "Баку · Центр профессионального развития",
    hero_title_line1: "Навыки, ведущие",
    hero_title_line2: "к реальной цели.",
    hero_subtitle:
      "От data science до языков — North Star Academy создаёт практические курсы вокруг того, что действительно продвигает вашу карьеру. Не просто сертификат, а реальный следующий шаг.",
    hero_cta_courses: "Все курсы",
    hero_cta_advisor: "Поговорить с консультантом",
  },
} as const;

export type UiStringKey = keyof typeof UI_STRINGS.en;
