export const UI_STRINGS = {
  en: {
    nav_courses: "Courses",
    nav_faq: "FAQ",
    nav_blog: "Blog",
    nav_apply: "Apply now",
    footer_explore: "Explore",
    footer_contact: "Contact",
    footer_courses: "Courses",
    footer_blog: "Blog",
    footer_faq: "FAQ",
    footer_certificates: "Certificates",
    footer_talk_advisor: "Talk to an advisor",
    footer_tagline: "Data science, analytics, and language bootcamps in Baku.",
    footer_rights: "All rights reserved.",
    hero_eyebrow: "Baku · Data Science · Analytics · Languages",
    hero_title_line1: "Skills that point",
    hero_title_line2: "somewhere real.",
    hero_subtitle:
      "Bootcamps in data science, analytics, and Python — plus English, Russian, and Excel courses built for people who want a clear next step, not just a certificate.",
    hero_cta_courses: "See all courses",
    hero_cta_advisor: "Talk to an advisor",
  },
  az: {
    nav_courses: "Kurslar",
    nav_faq: "FAQ",
    nav_blog: "Bloq",
    nav_apply: "İndi müraciət et",
    footer_explore: "Naviqasiya",
    footer_contact: "Əlaqə",
    footer_courses: "Kurslar",
    footer_blog: "Bloq",
    footer_faq: "FAQ",
    footer_certificates: "Sertifikatlar",
    footer_talk_advisor: "Məsləhətçi ilə danışın",
    footer_tagline: "Bakıda data elmi, analitika və dil bootcamp-ləri.",
    footer_rights: "Bütün hüquqlar qorunur.",
    hero_eyebrow: "Bakı · Data Elmi · Analitika · Dillər",
    hero_title_line1: "Real nəticəyə",
    hero_title_line2: "aparan bacarıqlar.",
    hero_subtitle:
      "Data elmi, analitika və Python bootcamp-ləri — həmçinin İngilis, Rus dili və Excel kursları. Sadəcə sertifikat üçün deyil, real növbəti addım üçün.",
    hero_cta_courses: "Bütün kursları gör",
    hero_cta_advisor: "Məsləhətçi ilə danış",
  },
  ru: {
    nav_courses: "Курсы",
    nav_faq: "Вопросы",
    nav_blog: "Блог",
    nav_apply: "Подать заявку",
    footer_explore: "Навигация",
    footer_contact: "Контакты",
    footer_courses: "Курсы",
    footer_blog: "Блог",
    footer_faq: "Вопросы",
    footer_certificates: "Сертификаты",
    footer_talk_advisor: "Поговорить с консультантом",
    footer_tagline: "Буткемпы по data science, аналитике и языкам в Баку.",
    footer_rights: "Все права защищены.",
    hero_eyebrow: "Баку · Data Science · Аналитика · Языки",
    hero_title_line1: "Навыки, ведущие",
    hero_title_line2: "к реальной цели.",
    hero_subtitle:
      "Буткемпы по data science, аналитике и Python — а также курсы английского, русского языков и Excel. Не просто сертификат, а реальный следующий шаг.",
    hero_cta_courses: "Все курсы",
    hero_cta_advisor: "Поговорить с консультантом",
  },
} as const;

export type UiStringKey = keyof typeof UI_STRINGS.en;
